version: "3.8"
services:
  # DB service
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DATABASE},${POSTGRES_DATABASE_TEST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ./scripts/pg-init.sh:/docker-entrypoint-initdb.d/pg-init.sh
      - postgres-data:/data/postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - postgres
    restart: unless-stopped

  # Db admin service
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

  # redis cache
  redis:
    container_name: redis_container
    image: redis:latest
    volumes:
      - ./config/redis.conf:/redis.conf
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "/redis.conf"]

volumes:
  postgres-data:
  pgadmin:
  redis-data:

networks:
  postgres:
    driver: bridge
